name: Deploy JupyterLite to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install JupyterLite
        run: pip install jupyterlite

      - name: Build JupyterLite site
        run: jupyter lite build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_output
